### PR TITLE
[YUNIKORN-977] Revert YUNIKORN-885 - Set heath check as liveness probe

### PR DESCRIPTION
**Pull request by craigcondit**
Revert "[YUNIKORN-885] Set health check as liveness probe (#48)"

This reverts commit 9b18a21e580faa5e2c1a8737cd64d972441d3320.

### CODE REVIEW

**Comment by craigcondit** [comment]
I will also backport this to 0.12 branch once approved as it is a blocker there.

**Comment by craigcondit** [comment]
@yuchaoran2011, can you review?

**Review by yangwwei — APPROVED** [review]
+1

**Comment by yangwwei** [comment]
Thank you @craigcondit , make sense. Approved the PR. Is this one causing [YUNIKORN-975](https://issues.apache.org/jira/browse/YUNIKORN-975) as well?

**Pull request closed without merging**
